CREATE TABLE PRODUTOS

(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(100) NOT NULL,
    QTDESTOQUE FLOAT NOT NULL,
    PRECO FLOAT NOT NULL,
    CATEGORIAID INT NOT NULL,
    FOREIGN KEY (CATEGORIAID) REFERENCES CATEGORIAS (ID)
)